CREATE TABLE `security` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `uid` INT,
  `security` VARCHAR(255),
  `iv` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;